version: "3.7"

networks:
  proxy:

volumes:
  postgres_data:

services:
  traefik:
    image: "traefik:1.7.2-alpine"
    container_name: "traefik"
    ports:
      - "80:80" # - Default Port
      - "443:443" # - SSL Port
      - "31951:31951" # - Mapproxy
      - "8000:8000" # - Traefik UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/config/traefik.toml:/etc/traefik/traefik.toml
      - ./app/config/ssl:/ssl
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.entryPoints=traefik-ui"
      - "traefik.frontend.rule=Host:localhost;"
      - "traefik.port=8080"
      - "traefik.enable=true"
    networks:
      proxy:

  client:
    build:
      dockerfile: Dockerfile
      context: ./app/client
    image: goat-client
    volumes:
      - /app/node_modules
      - ./app/client:/app
    container_name: goat-client
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.frontend.rule=Host:localhost;"
      - "traefik.port=80"
      - "traefik.enable=true"
    networks:
      proxy:

  api:
    build:
      context: ./app/api
    image: eliaspajares/goat-api:dev
    volumes:
      - /app/node_modules
      - ./app/api:/app
    container_name: goat-api
    env_file:
      - ./app/config/docker-env/api.env
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/api"
      - "traefik.port=3000"
      - "traefik.enable=true"
    networks:
      proxy:

  geoserver:
    image: goatcommunity/geoserver-base:2.17.2
    volumes:
      - ./app/geoserver/geoserver_data:/var/local/geoserver
      - ./app/geoserver/additional_libs:/var/local/geoserver-exts
    container_name: goat-geoserver
    restart: on-failure
    depends_on:
      - db
    labels:
      - "traefik.backend=geoserver"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/geoserver"
      - "traefik.port=8080"
      - "traefik.enable=true"
    networks:
      proxy:

  db: 
    image: goatcommunity/database:12-3.1-2.6.11-custom-2.3.14
    container_name: goat-database
    restart: on-failure
    volumes:
      # we are mounting a named volume here instead of a data directory path because of
      # a windows 10 premission issue. See https://github.com/docker-library/postgres/issues/435)
      # .........
      - postgres_data:/var/lib/postgresql
      - ./app/database:/opt
      - ./app/config:/opt/config
    env_file:
      - ./app/config/docker-env/db.env
    ports:
      - "65432:5432"
    networks:
      proxy:

  print:
    image: camptocamp/mapfish_print:3.16
    volumes:
      - ./app/print/templates:/usr/local/tomcat/webapps/ROOT/print-apps
    container_name: goat-print
    labels:
      - "traefik.backend=print"
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/print"
      - "traefik.port=8080"
      - "traefik.enable=true"
    networks:
      proxy:

  #This container is used for running cron jobs. It is mainly for production purposes.
  # cron:
  #   build:
  #     dockerfile: ./cron/Dockerfile
  #     context: ./app
  #   image: goat-cron
  #   volumes:
  #     - ./app/database:/opt
  #     - ./app/config:/opt/config
  #   container_name: goat-cron
  #   env_file:
  #     - ./app/config/docker-env/db.env
  #   networks:
  #     proxy:
